"use client";

import React, { useEffect, useLayoutEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { Loader2, ArrowUp, ArrowDown, ArrowUpDown, ChevronDown, Download, Info, X } from "lucide-react";
import DashboardHeader from "@/components/DashboardHeader";
import { useFilter } from "@/components/FilterContext";
import MetabaseProviderWrapper from "@/components/MetabaseProvider";
import MultiSelectDropdown from "@/components/MultiSelectDropdown";
import UsStateChoropleth from "@/components/UsStateChoropleth";
import { exportToCsv } from "@/lib/exportCsv";

// ─── Definitions modal ────────────────────────────────────────────────────────

const DEFINITIONS: { term: string; def: React.ReactNode }[] = [
  { term: "Filter",         def: "Filter by Campaign, Date Range, or State." },
  { term: "Reset",          def: <>Click <strong>Reset Filters</strong> to clear all selected filters.</> },
  { term: "Sort",           def: <>Sort the table by clicking any column header or using the <strong>Sort By</strong> menu.</> },
  { term: "Export",         def: <>Use <strong>Export All</strong> to export data from all dashboard views. Use <strong>Export</strong> within an individual dashboard to export data from that view only.</> },
  { term: "Engagements",    def: "Total engagement activity generated by users within each state." },
  { term: "Engaged Users",  def: "Unique users within each state who engaged with your content or campaign." },
  { term: "Leads",          def: "Content downloads by target personas within each state." },
];

function DefinitionsModal({ onClose }: { onClose: () => void }) {
  const [mounted, setMounted] = useState(false);
  useEffect(() => { setMounted(true); }, []);
  if (!mounted) return null;

  return createPortal(
    <div
      style={{ position: "fixed", inset: 0, zIndex: 9999, display: "flex", alignItems: "center", justifyContent: "center" }}
      onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div style={{ position: "absolute", inset: 0, background: "rgba(0,0,0,0.35)" }} onMouseDown={onClose} />
      <div
        style={{ position: "relative", background: "#fff", borderRadius: 16, boxShadow: "0 20px 60px rgba(0,0,0,0.18)", border: "1px solid #f0f0f0", padding: 24, maxWidth: 520, width: "calc(100% - 32px)" }}
        onMouseDown={(e) => e.stopPropagation()}
      >
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 16 }}>
          <span style={{ fontWeight: 700, fontSize: 11, letterSpacing: "0.08em", textTransform: "uppercase", color: "#111" }}>Dashboard Guide</span>
          <button type="button" onClick={onClose} style={{ color: "#9ca3af", cursor: "pointer", background: "none", border: "none", padding: 0 }}>
            <X size={16} />
          </button>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
          {DEFINITIONS.map(({ term, def }) => (
            <div key={term} style={{ display: "flex", gap: 12 }}>
              <span className="font-bold" style={{ fontSize: 12, color: "#111", flexShrink: 0, minWidth: 140, paddingTop: 1 }}>{term}</span>
              <span style={{ fontSize: 12, color: "#4b5563", lineHeight: 1.6 }}>{def}</span>
            </div>
          ))}
        </div>
      </div>
    </div>,
    document.body
  );
}

function fetchFieldOptions(field: "district" | "state") {
  return (q: string) =>
    fetch(`/api/filter-search?field=${field}&q=${encodeURIComponent(q)}`)
      .then((r) => r.json())
      .then((d) => d.values ?? []);
}

// ─── Sort dropdown ────────────────────────────────────────────────────────────

type SortDir = "asc" | "desc";
interface SortState { col: string; dir: SortDir }

const GEO_SORT_COLS = ["Engaged Users", "Engagements", "Leads", "State"];

function SortDropdown({ sort, onSort }: { sort: SortState; onSort: (s: SortState) => void }) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function handle(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener("mousedown", handle);
    return () => document.removeEventListener("mousedown", handle);
  }, []);

  return (
    <div ref={ref} className="relative">
      <button
        onClick={() => setOpen((o) => !o)}
        className="flex items-center gap-2 px-3 py-2 border border-gray-300 rounded-lg bg-white hover:border-blue-400 transition-colors"
      >
        <ArrowUpDown size={13} className="text-gray-400" />
        <span className="text-gray-400 text-[13px] font-bold uppercase tracking-wider">Sort by:</span>
        <span className="text-blue-600 font-semibold text-[13px]">{sort.col}</span>
        <span className="text-gray-400 text-xs">{sort.dir === "asc" ? "↑" : "↓"}</span>
        <ChevronDown size={13} className="text-gray-400 shrink-0" />
      </button>
      {open && (
        <div className="absolute top-full right-0 mt-1 bg-white border border-gray-200 rounded-xl shadow-lg z-50 min-w-[180px] py-1">
          {GEO_SORT_COLS.map((label) => {
            const active = sort.col === label;
            return (
              <button key={label}
                onClick={() => { onSort({ col: label, dir: active && sort.dir === "desc" ? "asc" : "desc" }); setOpen(false); }}
                className={`w-full flex items-center justify-between px-4 py-2.5 text-sm hover:bg-gray-50 ${active ? "text-blue-600 font-semibold" : "text-gray-600"}`}>
                {label}
                {active && (sort.dir === "asc" ? <ArrowUp size={12} /> : <ArrowDown size={12} />)}
              </button>
            );
          })}
        </div>
      )}
    </div>
  );
}

// ─── Engagements by Geography ──────────────────────────────────────────────────

type Col = { display_name: string; base_type: string };
type GeoRow = (string | number | null)[];
const NUMBER_TYPES = new Set(["type/Integer","type/BigInteger","type/Float","type/Decimal","type/Number"]);
const GEO_LEFT_ALIGN_COLS = new Set<string>();

function GeographyTable({
  campaign, dateStart, dateEnd, filterDistrict, filterState, selectedState, setSelectedState, sort, setSort,
}: {
  campaign: string[]; dateStart: string; dateEnd: string;
  filterDistrict: string[]; filterState: string[];
  selectedState: string | null; setSelectedState: (s: string | null) => void;
  sort: SortState; setSort: (s: SortState) => void;
}) {
  const [cols, setCols] = useState<Col[]>([]);
  const [rows, setRows] = useState<GeoRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const titleBarRef = useRef<HTMLDivElement>(null);
  const [titleBarHeight, setTitleBarHeight] = useState(0);

  useLayoutEffect(() => {
    const el = titleBarRef.current;
    if (!el) return;
    const measure = () => { const h = el.offsetHeight; if (h > 0) setTitleBarHeight(h); };
    measure();
    const ro = new ResizeObserver(measure);
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  useEffect(() => {
    setLoading(true);
    setError("");
    const params = new URLSearchParams();
    if (dateStart) params.set("dateStart", dateStart);
    if (dateEnd)   params.set("dateEnd", dateEnd);

    if (filterDistrict.length > 0) {
      // District filter active — fetch district-level data, then aggregate by state.
      // Campaign filter is applied server-side via Abmi_Campaign column.
      params.set("district", filterDistrict.join(","));
      if (campaign.length) params.set("campaign", campaign.join(","));
      fetch(`/api/q168-data?${params.toString()}`)
        .then((r) => r.json())
        .then((d: { cols?: Col[]; rows?: GeoRow[] }) => {
          const rawCols  = d.cols  ?? [];
          const rawRows  = d.rows  ?? [];
          const stateIdx = rawCols.findIndex((c) => c.display_name === "State");
          const engIdx   = rawCols.findIndex((c) => c.display_name === "Engagements");
          const leadsIdx = rawCols.findIndex((c) => c.display_name === "Leads");

          // Campaign already filtered server-side — use all returned rows directly.
          const campFiltered = rawRows;

          // Aggregate by state
          const byState = new Map<string, { engaged: number; leads: number }>();
          for (const row of campFiltered) {
            const state = String(row[stateIdx] ?? "");
            if (!state) continue;
            if (!byState.has(state)) byState.set(state, { engaged: 0, leads: 0 });
            const t = byState.get(state)!;
            t.engaged += Number(row[engIdx])   || 0;
            t.leads   += Number(row[leadsIdx]) || 0;
          }

          setCols([
            { display_name: "State",         base_type: "type/Text"    },
            { display_name: "Engaged Users",  base_type: "type/Integer" },
            { display_name: "Leads",          base_type: "type/Integer" },
          ]);
          setRows([...byState.entries()].map(([state, { engaged, leads }]) => [state, engaged, leads]));
          setSort({ col: "Engaged Users", dir: "desc" });
          setLoading(false);
        })
        .catch((err: Error) => { setError(err.message ?? "Failed to load"); setLoading(false); });
      return;
    }

    // No district filter — use Card 169 state-level aggregated data.
    if (campaign.length) params.set("campaign", campaign.join(","));
    fetch(`/api/q169-data?${params.toString()}`)
      .then((r) => r.json())
      .then((d) => { setCols(d.cols ?? []); setRows(d.rows ?? []); setLoading(false); })
      .catch((err: Error) => { setError(err.message ?? "Failed to load"); setLoading(false); });
  }, [campaign, dateStart, dateEnd, filterDistrict]);

  const stateCol = cols.findIndex((c) => c.display_name === "State");

  // Client-side state filter — Metabase aggregates one row per state so this
  // is instant and also keeps the map in sync with the selected filter.
  const filteredRows = filterState.length > 0 && stateCol >= 0
    ? rows.filter((row) => filterState.some((s) => s.toLowerCase() === String(row[stateCol] ?? "").toLowerCase()))
    : rows;

  const sortColIdx = cols.findIndex((c) => c.display_name === sort.col);
  const effectiveSortIdx = sortColIdx >= 0 ? sortColIdx : 1;
  const sorted = [...filteredRows].sort((a, b) => {
    const av = a[effectiveSortIdx]; const bv = b[effectiveSortIdx];
    if (av === null || av === undefined) return 1;
    if (bv === null || bv === undefined) return -1;
    const cmp = typeof av === "number" && typeof bv === "number"
      ? av - bv : String(av).localeCompare(String(bv));
    return sort.dir === "asc" ? cmp : -cmp;
  });

  const engagedUsersCol = cols.findIndex((c) => c.display_name === "Engaged Users");
  const valueByState: Record<string, number> = {};
  if (stateCol >= 0 && engagedUsersCol >= 0) {
    for (const row of filteredRows) {
      const state = String(row[stateCol] ?? "");
      const value = Number(row[engagedUsersCol]) || 0;
      if (state) valueByState[state] = value;
    }
  }

  const totals = cols.map((col, j) => {
    if (j === stateCol) return "Grand total";
    if (!NUMBER_TYPES.has(col.base_type)) return "";
    return filteredRows.reduce((sum, row) => sum + (Number(row[j]) || 0), 0);
  });

  const displayName = (name: string) => name;

  return (
    <div>
      <div ref={titleBarRef} className="sticky top-0 z-20 bg-gray-900 text-white px-5 py-3 rounded-t-xl flex items-center justify-between">
        <span className="font-bold text-sm tracking-wide uppercase">Engagements By Geography</span>
        {filteredRows.length > 0 && (
          <button
            onClick={() => exportToCsv("DATIA ABMxi-Engagements-by-Geography", cols, filteredRows)}
            className="flex items-center gap-1.5 text-xs text-gray-300 hover:text-white transition-colors"
          >
            <Download size={13} /> Export
          </button>
        )}
      </div>
      {loading && (
        <div className="flex items-center justify-center h-48 gap-2 text-gray-400 text-sm bg-white border border-t-0 border-gray-200 rounded-b-xl">
          <Loader2 size={18} className="animate-spin" /> Loading…
        </div>
      )}
      {!loading && error && (
        <div className="flex items-center justify-center h-48 text-red-500 text-sm bg-white border border-t-0 border-gray-200 rounded-b-xl">{error}</div>
      )}
      {!loading && !error && (
        <div className="border border-t-0 border-gray-200 rounded-b-xl shadow-sm bg-white" style={{ clipPath: "inset(0 round 0 0 0.75rem 0.75rem)" }}>
          {filteredRows.length === 0 ? (
            <div className="flex items-center justify-center h-48 text-gray-400 text-sm bg-white">No results</div>
          ) : (
            <div className="flex flex-col lg:flex-row gap-4 p-4">
              <div className="lg:w-1/2 shrink-0 flex items-start">
                <UsStateChoropleth
                  valueByState={valueByState}
                  selectedState={selectedState ?? undefined}
                  onStateClick={(abbr) => setSelectedState((s) => s === abbr ? null : abbr)}
                />
              </div>
              <div className="lg:w-1/2 min-w-0 overflow-auto">
                <table className="text-sm border-collapse w-full">
                  <thead>
                    <tr className="border-b border-gray-200">
                      <th className="px-3 py-2 text-center w-10 font-semibold whitespace-nowrap" style={{ color: "#111827" }}>#</th>
                      {cols.map((col, j) => {
                        const isLeft = GEO_LEFT_ALIGN_COLS.has(col.display_name);
                        const active = sort.col === col.display_name;
                        return (
                          <th key={j}
                            onClick={() => setSort({ col: col.display_name, dir: active && sort.dir === "desc" ? "asc" : "desc" })}
                            className={`px-4 py-3 font-semibold whitespace-nowrap cursor-pointer select-none hover:opacity-70 ${isLeft ? "text-left" : "text-center"}`}
                            style={{ color: "#111827" }}
                          >
                            <span className={`inline-flex items-center gap-1 ${isLeft ? "justify-start" : "justify-center"}`}>
                              {displayName(col.display_name)}
                              {active
                                ? sort.dir === "asc" ? <ArrowUp size={11} /> : <ArrowDown size={11} />
                                : <ArrowUpDown size={11} className="opacity-30" />}
                            </span>
                          </th>
                        );
                      })}
                    </tr>
                  </thead>
                  <tbody>
                    {sorted.map((row, i) => {
                      const rowState = stateCol >= 0 ? String(row[stateCol] ?? "") : "";
                      const isActive = rowState && rowState === selectedState;
                      return (
                        <tr
                          key={i}
                          onClick={() => setSelectedState((s) => s === rowState ? null : rowState)}
                          className={`border-b border-gray-100 cursor-pointer transition-colors ${isActive ? "bg-orange-50" : "hover:bg-gray-50"}`}
                        >
                          <td className={`px-3 py-1.5 text-center text-xs w-10 shrink-0 ${isActive ? "text-orange-500 font-bold" : "text-gray-400"}`}>{i + 1}</td>
                          {row.map((cell, j) => {
                            const isNum = NUMBER_TYPES.has(cols[j]?.base_type);
                            const isLeft = GEO_LEFT_ALIGN_COLS.has(cols[j]?.display_name ?? "");
                            return (
                              <td key={j} className={`px-4 py-1.5 ${isLeft ? "text-left" : "text-center"} ${isNum ? "tabular-nums" : ""} ${isActive ? "text-orange-700 font-semibold" : "text-gray-800"}`}>
                                {cell === null || cell === undefined ? "" : String(cell)}
                              </td>
                            );
                          })}
                        </tr>
                      );
                    })}
                  </tbody>
                  <tfoot>
                    <tr className="border-t-2 border-gray-300 font-bold">
                      <td className="px-3 py-2"></td>
                      {totals.map((val, j) => {
                        const isLeft = GEO_LEFT_ALIGN_COLS.has(cols[j]?.display_name ?? "");
                        return (
                          <td key={j} className={`px-4 py-2 ${isLeft ? "text-left" : "text-center tabular-nums"} text-gray-900`}>
                            {typeof val === "number" ? val.toLocaleString() : val}
                          </td>
                        );
                      })}
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

function GeoInsightsContent() {
  const { campaign, dateStart, dateEnd, resetSignal } = useFilter();

  const [filterDistrict, setFilterDistrict] = useState<string[]>([]);
  const [filterState, setFilterState] = useState<string[]>([]);
  const [selectedState, setSelectedState] = useState<string | null>(null);
  const [showDefs, setShowDefs] = useState(false);
  const [sort, setSort] = useState<SortState>({ col: "Engaged Users", dir: "desc" });

  useEffect(() => {
    if (resetSignal === 0) return;
    setFilterDistrict([]);
    setFilterState([]);
    setSelectedState(null);
  }, [resetSignal]);

  return (
    <div style={{ position: "fixed", top: 0, left: "12rem", right: 0, bottom: 0,
                  display: "flex", flexDirection: "column", background: "#f9fafb", zIndex: 1 }}>
      {showDefs && <DefinitionsModal onClose={() => setShowDefs(false)} />}
      <div style={{ flexShrink: 0, padding: "16px 24px 0" }}>
        <DashboardHeader />

        {/* Filter row */}
        <div className="flex items-center gap-2 mb-3">
          <MultiSelectDropdown label="State" value={filterState} onChange={(v) => { setFilterState(v); setFilterDistrict([]); }} search={fetchFieldOptions("state")} />
          <div className="ml-auto flex items-center gap-2">
            <button type="button" onClick={() => setShowDefs(true)}
              className="flex items-center gap-1.5 px-3 py-2 text-xs text-gray-500 hover:text-gray-800 border border-gray-200 hover:border-gray-400 rounded-lg bg-white transition-colors">
              <Info size={13} />
              Dashboard Guide
            </button>
            <SortDropdown sort={sort} onSort={setSort} />
          </div>
        </div>
      </div>

      <div style={{ flex: 1, minHeight: 0, overflow: "auto", padding: "0 24px 24px" }}>
        <GeographyTable
          campaign={campaign}
          dateStart={dateStart}
          dateEnd={dateEnd}
          filterDistrict={filterDistrict}
          filterState={filterState}
          selectedState={selectedState}
          setSelectedState={setSelectedState}
          sort={sort}
          setSort={setSort}
        />
      </div>
    </div>
  );
}

export default function Page() {
  return (
    <MetabaseProviderWrapper>
      <GeoInsightsContent />
    </MetabaseProviderWrapper>
  );
}
